Chore/issue#12: 프로젝트 Set Up
kakao-tech-campus-2nd-step3/Team23_BE pull request #13
Opened 2024-09-21 20:04 UTC by minju26

## PR
### ✨ 작업 내용
- 본격 기능 개발에 앞서, 공통으로 사용할 요소에 대한 설정을 했습니다.
- 도메인 클래스를 정의했습니다.
   - ERD를 바탕으로 기본적인 필드들은 모두 채워두었습니다.
   - 지금 생각 해 봤을 때 필요할 것 같은 **양방향 맵핑**은 반영해뒀습니다. 단방향 중에서는 개발 중에 참조가 필요하게 된다면 추가하면 될 것 같습니다.
   - 확인은 했지만, **빠졌거나 수정이 필요한 부분 피드백 부탁드립니다!**
- API 명세 문서화를 위해 **Swagger**를 사용했습니다.
   - 당장은 로컬에서 사용할 것 같아 그냥 주소를 명시해뒀습니다.
   - 배포가 완료된 시점에는 properties 파일로 주소를 관리하고 서버 주소 리스트에 추가하겠습니다.

### 🔍 참고 사항
- 공통으로 사용할 api response 구조를 간단하게 설정하려고 했는데, 회의가 필요할 것 같아 일단 정의하지 않았습니다.
- 이미 로컬에서 작업중이시라면, 본 PR이 Weekly/4 브랜치에 머지 된 후 `꼭 변경사항 반영`해주세요!

### 🐞현재 버그
x

### #️⃣ 연관 이슈(Git Close)
- #12 
___
### 😊 리뷰 규칙을 지킵시다
코드 리뷰는 `Pn`룰에 따라 작성하기.   
Reviewer가 피드백을 남길 때 Assignee에게 얼마나 해당 피드백에 대해 강조하고 싶은 지 표현하기 위한 규칙입니다.
- `P1` : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
- `P2` : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
- `P3` : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-09-22 05:43 UTC, dkswoals requested changes
고생 하셨습니다!!
수정 사항 남겨두었습니다.

2024-09-22 05:43 UTC, dkswoals commented on src/main/java/kappzzang/jeongsan/domain/Expense.java
> +    @OneToMany(mappedBy = "expense")
P1: Expense, Group, Member 엔티티에 `created_at`, `updated_at` 컬럼이 추가되어야 할 것 같습니다!
이전에 erd 작성 때에 우석님이 언급하신 것처럼 BaseEntity로 추가 시키는 거 어떨까요?

[https://kakao-techcampus-2.slack.com/archives/C07GFNTHSBV/p1724999738184109](https://github.com/kakao-tech-campus-2nd-step3/Team23_BE/pull/13/url)

2024-09-22 07:47 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/domain/Expense.java
> +    @OneToMany(mappedBy = "expense")
앗 그러네요! 반영하도록 하겠습니다

2024-09-23 11:00 UTC, us4c0d3 approved these changes, later dismissed
재민님이 남겨주신 리뷰로 충분한 것 같습니다!

2024-09-23 11:00 UTC, us4c0d3 commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
👍 
오늘 내로 AWS RDS + MySQL 설정해서 알려드리겠습니다

2024-09-23 11:02 UTC, Lucerna00 approved these changes, later dismissed
수고 많으셨습니다!
- group은 예약어이지만 지금처럼 처리해서 사용해도 괜찮을 것 같습니다. 
- 그리고 expense도 일반적이고 광범위하게 사용된다고 해서 저는 그대로 써도 된다고 생각합니다.

2024-09-23 12:54 UTC, dkswoals submitted a review, later dismissed
고생하셨습니다~!

2024-09-23 15:13 UTC, Lucerna00 reviewed
고려해야 할 사항을 작성해 두었습니다

2024-09-23 15:13 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/domain/BaseEntity.java
> +@NoArgsConstructor
P2: 무분별한 객체 생성을 방지하기 위해 엔티티 생성자가 public보단 protected로 하는 것이 더 좋다고 생각합니다.

```suggestion
@NoArgsConstructor(access = AccessLevel.PROTECTED)
```

2024-09-23 15:45 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/domain/BaseEntity.java
> +@NoArgsConstructor
네, 베이스 엔티티는 서브 클래스를 통해서 객체가 생성되도록 해야겠네요. 반영하도록 하겠습니다

2024-09-24 00:55 UTC, us4c0d3 approved these changes, later dismissed
group 테이블 관련하여 이번 주에 BE끼리 회의를 간단하게 진행하면 좋을 것 같습니다.

여유가 안된다면 카톡방 or 슬랙에서 의견을 교류해도 될 것 같습니다

2024-09-24 00:55 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/domain/Group.java
> +public class Group extends BaseEntity {
p3: 예약어 대신 `team`은 어떨까요? 해당 부분은 추후 회의를 통해 결정하도록 하는 것이 좋을 것 같습니다!

2024-09-24 02:28 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/domain/Group.java
> +public class Group extends BaseEntity {
넵 일단 team으로 수정해뒀습니다

2024-09-24 02:31 UTC, us4c0d3 approved these changes

2024-09-24 02:36 UTC, Lucerna00 approved these changes

2024-09-24 02:39 UTC, merged