Feature/issue#14: custom api response, exception handler 구현
kakao-tech-campus-2nd-step3/Team23_BE pull request #19
Opened 2024-09-24 15:30 UTC by minju26

## PR
### ✨ 작업 내용
- 응답 구조 통일을 위한 api response 구현
- 성공/실패 경우에 대해 상세 사항을 정의하기 위한 type 클래스 정의
- global exception과 그 handler 구현
- 기타 사소한 수정(lombok, 빠진 import, pr 템플릿 등)

### 🔍 참고 사항
- 공통 api response를 어떻게 활용하면 좋을지 예시를 담은 컨트롤러(`ExampleController`)가 있습니다.
- 회의에서 **ErrorCode 클래스**를 정의하자고 했었는데, **errorCode 필드와 이름이 중복**되어 `ErrorType`으로 변경했습니다.
- **성공**의 경우에도 다양한 상황이 있을 수 있다고 생각하여 Error와 같이 **Type을 정의**했습니다.
- 개발 중 **본인이 사용할 Success/Error Type을 정의**해 사용하면 될 것 같습니다.

### ⚠️ 의논 필요
- `common` 패키지가 생기면서 구조를 아래와 같이 수정했는데, **패키지 구조에 대한 의견**이 있다면 자유롭게 코멘트 해주세요!   
(ex) exception 패키지로 관련 클래스 묶기, config도 common 하위로 이동 등

   ```
   common
   ├── enumeration
   │   └── [Enum classes]
   ├── GlobalExceptionHandler.java
   ├── JeongsanApiResponse.java
   └── JeongsanException.java

- 일단 `JeonsanException` 발생 시 바로 failure reponse를 담아 전달했습니다. 바로 전달하지 않고 catch 한 뒤 다른 작업을 할 수 있도록 할까요?

### 🐞현재 버그
X

### #️⃣ 연관 이슈(Git Close)
- close #14 
___
### 😊 리뷰 규칙을 지킵시다
코드 리뷰는 `Pn`룰에 따라 작성하기.   
Reviewer가 피드백을 남길 때 Assignee에게 얼마나 해당 피드백에 대해 강조하고 싶은 지 표현하기 위한 규칙입니다.
- `P1` : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
- `P2` : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
- `P3` : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-09-24 15:37 UTC, minju26 commented
ci 스크립트가 `Master` 브랜치에 있는 스크립트로 실행되고 있어서 지금 수정해도 반영이 안되네요..
베이스 엔티티의 접근 제한자 쪽에서 에러가 나고 있는데, 아마 gradle caching 때문인 것 같아요
(로컬에서 `./gradlew clean build` 하면 BUILD SUCCESSFUL 이 뜹니다)

1. 일단 그냥 머지 한다...
2. 스크립트 수정 PR만 생성해서 급히 마스터에 반영한다..

2024-09-24 16:32 UTC, dkswoals reviewed
고생하셨습니다! 코드는 전체적으로 깔끔하게 잘 작성해주신 것 같습니다
- 패키지 구조에 대한 의견 : 
common.exception에 헨들러와 커스텀 예외 등을 모아두면 좋을듯 합니다!

- 현재 오류에 대해서는 제가 잘 아는 부분은 아니지만
정 방법이 없다면 마스터에 수정 PR하는 방법도 동의합니다!

2024-09-24 17:29 UTC, Lucerna00 reviewed
덕분에 response를 깔끔하게 할 수 있을 것 같습니다!

- global 패키지가 있어도 괜찮을 것 같습니다.
```
global
├── common
│   └── enumeration
├── config
├── exception
└── util
```

- failure reponse만 해도 괜찮다고 생각합니다.

- Actions에서 Weekly/4에 있는 캐시를 삭제해도 안 되면 따로 PR을 만들어 수정하는 것이 좋겠습니다.

2024-09-24 17:29 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/common/JeongsanException.java
> +
P2: 불필요한 줄바꿈이 있습니다.

2024-09-24 17:29 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/common/GlobalExceptionHandler.java
> +        exception.printStackTrace();
P3: logging을 써봐도 좋을 것 같습니다.

2024-09-24 18:09 UTC, us4c0d3 requested changes
CI 오류 해결 방법과 일부 수정사항 남겼습니다!

CI 오류 해결의 경우 Lombok이 처음이라 정확하지 않을 수 있어 커밋을 통해 테스트해보는 것을 권장드립니다

2024-09-24 18:09 UTC, us4c0d3 commented on .github/workflows/ci.yml
P1: 캐싱의 문제는 아닌 것으로 보입니다.

에러 발생이 Lombok 혹은 어노테이션으로 인해 발생한 것으로 추정되는데, `build.gradle`에 아래 코드를 추가해서 커밋해 테스트해볼 수 있을까요?

```
configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}
```
이는 자바 컴파일 단계에서 어노테이션에 정의된 프로세스를 실행하기 때문에 빌드 과정에서의 오류를 줄일 수 있습니다.

2024-09-24 18:09 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/common/GlobalExceptionHandler.java
> +        exception.printStackTrace();
P2: 프린트문은 성능 오버헤드가 있습니다 logging을 사용하는 것이 권장됩니다.

2024-09-24 18:09 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/common/enumeration/ErrorType.java
> +    private final String message;
P1: `httpStatusCode`는 `int`가 아닌 `HttpStatusCode`를 사용하는 것이 좋을 것 같습니다.

타입을 `HttpStatusCode`로 사용하면 enum 원소의 첫 번째 인자에 `.value()`없이 `HttpStatus.NOT_FOUND`만 작성해도 됩니다.

2024-09-24 18:09 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/common/enumeration/SuccessType.java
> +    SuccessType(int httpStatusCode, String message) {
P1: `ErrorType`과 동일

2024-09-25 05:14 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/common/JeongsanException.java
> +
오..! 디테일하시군요

2024-09-25 05:16 UTC, minju26 commented
> CI 오류 해결 방법과 일부 수정사항 남겼습니다!
> 
> CI 오류 해결의 경우 Lombok이 처음이라 정확하지 않을 수 있어 커밋을 통해 테스트해보는 것을 권장드립니다

네! PR 내용 읽어보시고 `의논 필요` 내용에 대한 의견도 부탁드립니다

2024-09-25 05:16 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/common/enumeration/ErrorType.java
> +    private final String message;
오 그렇군요 반영하도록 하겠습니다

2024-09-25 05:17 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/common/GlobalExceptionHandler.java
> +        exception.printStackTrace();
넵 비교해보고 고려해보도록 하겠습니다!

2024-09-25 05:17 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/common/GlobalExceptionHandler.java
> +        exception.printStackTrace();
넵 비교해보고 고려해보도록 하겠습니다!

2024-09-25 05:17 UTC, minju26 commented on .github/workflows/ci.yml
한번 시도 해보겠습니다!

2024-09-25 05:24 UTC, minju26 commented
> 덕분에 response를 깔끔하게 할 수 있을 것 같습니다!
> 
> * global 패키지가 있어도 괜찮을 것 같습니다.
> 
> ```
> global
> ├── common
> │   └── enumeration
> ├── config
> ├── exception
> └── util
> ```
> 
> * failure reponse만 해도 괜찮다고 생각합니다.
> * Actions에서 Weekly/4에 있는 캐시를 삭제해도 안 되면 따로 PR을 만들어 수정하는 것이 좋겠습니다.

(단순궁금)
혹시 `global`과 `common`이 어떤 점에서 명확히 나눠지는지 알려주실 수 있을까요?!
프로젝트 규모에 따라 common에 너무 항목이 많아질 수 있어서 global을 둬 확장성을 고려 하는걸까요?
어떤 점에서 해당 구조를 제시 하시는 것인지 궁금합니다~

2024-09-25 05:41 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/common/enumeration/ErrorType.java
> +    private final String message;
제시해 주신 의견이 `HttpStatusCode`를 사용하면 int를 사용하지 않아도 숫자 코드가 적용된다고 이해했는데, 적용 해보니 아래처럼 `"CREATED"` 이런 문자열로 나오네요!
제가 이해한 것과 다른 의도로 말씀 해주신걸까요??

```
{
  "status": "success",
  "httpCode": "CREATED",
  "message": "모임이 생성되었습니다."
}
```

2024-09-25 05:44 UTC, minju26 commented on .github/workflows/ci.yml
흠.. 안되네요..🥲 추가한 내용을 삭제하지는 않고, 다른 해결 방법을 찾아 보겠습니다

2024-09-25 06:23 UTC, Lucerna00 commented
> (단순궁금) @Lucerna00 혹시 `global`과 `common`이 어떤 점에서 명확히 나눠지는지 알려주실 수 있을까요?! 프로젝트 규모에 따라 common에 너무 항목이 많아질 수 있어서 global을 둬 확장성을 고려 하는걸까요? 어떤 점에서 해당 구조를 제시 하시는 것인지 궁금합니다

둘 다 프로젝트 전반에 사용되는 클래스를 모아두는 패키지를 의미하지만
common은 상수나 response를 두는 패키지이면 좋겠다고 생각하였습니다.
그래서 설정이나 에러 관련은 common에 두기 애매하다고 생각하여 global이라는 상위 패키지를 만들었습니다.
또 무엇보다 말씀하신 것처럼 확장성을 고려하여 세분화하였습니다.

2024-09-25 06:26 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/common/enumeration/ErrorType.java
> +    private final String message;
엇 제가 알고있는 거랑 다르네요.. 저도 다시 확인해보고 말씀해드리겠습니다!

다만 그래도 HttpStatusCode를 사용하는 것이 좋다고생각합니다.
추후 E2E테스트 코드를 작성할 때 HttpStatus의 내부 메서드인 `is2xxsuccessful`과 같은 메서드를 사용할 수 있습니다!

2024-09-25 11:58 UTC, us4c0d3 commented
의논 필요부분은 

1. 패키지 구조의 경우 준석님의 의견이 추후 도메인을 분리하거나 했을 때도 확장성에 큰 도움이 것이라고 생각됩니다!
2. 에러 발생 경위를 어쨌든 프론트에 전달할 필요가 있으니 그대로 두셔도 될 것 같습니다.

2024-09-26 07:50 UTC, us4c0d3 reviewed
P2 수정 사항 남겼습니다~

2024-09-26 07:50 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/global/common/enumeration/SuccessType.java
> +        this.httpStatus = httpStatus;
P2: 이 부분도 ErrorType과 같이 HttpStatusCode를 사용하는 것이 좋을 것 같습니다.

2024-09-26 07:50 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
> +        this.httpStatus = httpStatus;
P2: 부모 클래스의 메서드 (`isSameCodeAs`, `valueOf`)를 사용하게 될 지는 모르겠으나 확장성을 고려했을 때 선언 타입을 부모 클래스인 `HttpStatusCode`를 사용하는 게 어떨까요?

```suggestion
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "000", "사용자를 찾을 수 없습니다.");

    private final HttpStatusCode httpStatusCode;
    private final String errorCode;
    private final String message;

    ErrorType(HttpStatusCode httpStatusCode, String errorCode, String message) {
        this.httpStatusCode = httpStatusCode;
```

2024-09-26 08:13 UTC, us4c0d3 approved these changes
👍

2024-09-26 08:29 UTC, dkswoals approved these changes
고생하셨습니다!

2024-09-26 08:29 UTC, dkswoals commented on src/main/java/kappzzang/jeongsan/global/common/JeongsanApiResponse.java
> +    }
JeongsanApiResponse 내부 반환에서 ResponseEntity에 감싸는 아이디어 좋은 거 같아요👍👍

2024-09-26 10:26 UTC, merged