Feature/issue#17: JWT 인증/인가
kakao-tech-campus-2nd-step3/Team23_BE pull request #33
Opened 2024-09-30 08:39 UTC by Lucerna00

## PR
### ✨ 작업 내용
- Spring Security + JWT를 활용한 인증/인가 구현

### 🔍 참고 사항
- SecurityConfig 설정으로 `/api/members/token` 경로만 토큰 없이 접근 가능하도록 하였습니다.
- `JwtAuthenticationFilter`에서 헤더에 있는 토큰을 추출하여 `AuthenticationManager`로 전달합니다.
- `AuthenticationManager`에 지정된 `JwtAuthenticationProvider`로 토큰의 클레임을 추출하여 인증된 사용자의 정보인 `JwtAuthenticationToken`을 생성하고 반환합니다.
- 로그인한 사용자의 정보를 다루기 위해 `JwtAuthenticationToken`을 활용하여 어노테이션을 만들 계획입니다.

### ⚠️ 의논 필요
X

### 🐞현재 버그
X

### #️⃣ 연관 이슈(Git Close)
- close #17 
___
### 😊 리뷰 규칙을 지킵시다
코드 리뷰는 `Pn`룰에 따라 작성하기.   
Reviewer가 피드백을 남길 때 Assignee에게 얼마나 해당 피드백에 대해 강조하고 싶은 지 표현하기 위한 규칙입니다.
- `P1` : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
- `P2` : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
- `P3` : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-09-30 16:27 UTC, minju26 requested changes
단순한 로직이 아닌데, 수고하셨습니다 👍
- SecurityContextHolder에 인증된 Authentication 객체를 저장하면 컨트롤러에서 해당 객체를 가져와서 쓸 수 있는걸로 알고 있습니다. 따로 인증된 객체에 대한 어노테이션은 필요 없을 것 같아요!

2024-09-30 16:27 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
> +    JWT_ILLEGAL_ARGUMENT(HttpStatus.BAD_REQUEST, "000", "토큰이 비어있습니다.");
P2: 클라이언트에서 유효하지 않은 토큰(자격증명)을 제공 했을 때, `401 UNAUTHORIZED` 를 쓰는 것이 조금 더 적절할 것 같습니다!

2024-09-30 16:27 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/global/config/SecurityConfig.java
> +            .csrf((config) -> config.disable())
P3: 추가 설정이 없이 `disable()`만 사용하는 경우, 메소드 참조 형식은 어떤가요?
```
 .formLogin(AbstractHttpConfigurer::disable)
 .httpBasic(AbstractHttpConfigurer::disable)
 .csrf(AbstractHttpConfigurer::disable)
 ```

2024-09-30 16:27 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/global/config/SecurityConfig.java
> +                .requestMatchers("/api/members/token", "/api/test/*")
(참고) 허용 경로가 바로 노출되니, 개발 마무리 단계에서는 properties 파일로 관리하고 리스트로 불러와도 좋겠네요!

2024-09-30 16:27 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/global/config/SecurityConfig.java
> +            .addFilterBefore(new JwtAuthenticationFilter(authenticationManagerBuilder.getOrBuild()), LogoutFilter.class)
(궁금) 토큰 검증 필터를 로그아웃 필터 앞에 배치한 이유가 있을까요??
개인적으로는, 로그아웃이 우선 되어야 로그아웃 요청 시 토큰이 무효화 되고 뒤에 인증이 제대로 처리될 것 같다는 생각입니다!

2024-09-30 16:27 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/global/security/JwtAuthenticationFilter.java
> +    }
P3: 아직 토큰을 만드는 로직은 없는 것 같은데, 추가된다면 토큰 생성과 토큰 추출 등의 기능들은 필터보다는 `jwtUtil` 또는 `jwtProvider` 같은 클래스에서 관리하면 좋을 것 같아요!

2024-09-30 16:27 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/global/security/JwtAuthenticationProvider.java
> +    }
P3: 지원 타입이 아닌 경우 발생하는 예외 처리도 있으면 좋을 것 같습니다!

2024-09-30 16:30 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/global/security/JwtAuthenticationFilter.java
> +    }
+ 추가로, 토큰 생성 없이 필터 작동 어떻게 테스트 하셨는지 궁금합니다!!

2024-09-30 18:16 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
> +    JWT_ILLEGAL_ARGUMENT(HttpStatus.BAD_REQUEST, "000", "토큰이 비어있습니다.");
토큰과 관련 있다 보니 400보단 401이 낫겠네요
그리고 JWT_ILLEGAL_ARGUMENT는 사용하지 않기에 삭제하겠습니다 (filter에서 토큰이 null인 경우가 처리되기 때문)
+) `@AuthenticationPrincipal`을 사용하면 말씀처럼 `Authentication`을 들고 올 수 있습니다. 다만 `Authentication`에는 현재 사용자 이름밖에 없어서 member 객체가 필요하다면 커스텀하려고 했습니다!

2024-09-30 18:16 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/global/config/SecurityConfig.java
> +            .csrf((config) -> config.disable())
아주 좋습니다

2024-09-30 18:16 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/global/config/SecurityConfig.java
> +                .requestMatchers("/api/members/token", "/api/test/*")
properties로 관리하는 것이 낫겠네요👍

2024-09-30 18:17 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/global/config/SecurityConfig.java
> +            .addFilterBefore(new JwtAuthenticationFilter(authenticationManagerBuilder.getOrBuild()), LogoutFilter.class)
솔직히 말씀드리면 특별한 이유는 없습니다😑
그리고 저희가 JWT을 사용하기에 `LogoutFilter` 앞뒤는 크게 상관없을 것 같습니다 (`LogoutFilter` 보단 토큰 블랙리스트 등으로 처리하기 때문)
그래도 보통 커스텀 필터를 `LogoutFilter` 뒤나 `UsernamePasswordAuthenticationFilter` 앞에 두기에 그렇게 수정하겠습니다!

2024-09-30 18:17 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/global/security/JwtAuthenticationFilter.java
> +    }
네 토큰 생성, 추출은 util로 따로 빼겠습니다

테스트는 https://jwt.io/ 와 Postman을 이용하여 진행하였습니다
util 생성 후 테스트 코드도 작성해 봐야겠네요

2024-09-30 18:17 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/global/security/JwtAuthenticationProvider.java
> +    }
여러 `AuthenticationProvider` 중 요청된 `Authentication`에 적합한 하나를 고르기 위해 필요한 메서드이므로 예외 처리할 필요가 없다고 생각합니다..!

2024-10-01 01:55 UTC, dkswoals submitted a review, later dismissed
민주님이 남겨주신 피드백으로 충분한 것 같습니다(jwt 관련 로직 분리 등등)
공부할 게 많은 기능이었을 텐데 정말 고생 많으셨습니다👍

남겨주신 의견에 대해서
다같이 의논해봐야 하겠지만 저의 의견은
- 사용자Id만으로 충분할거라 생각합니다
- 사용자 권한은 기본적인 기능 구현 이후
  일반 회원, 유료 회원(개선 버전 OCR), 어드민(회원 관리?) 정도로 나누면 될 것 같습니다

2024-10-01 06:05 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
> +    JWT_ILLEGAL_ARGUMENT(HttpStatus.BAD_REQUEST, "000", "토큰이 비어있습니다.");
그렇군요! 재민님과 같은 의견으로, 저도 memberId만 있으면 충분할 것 같습니다

2024-10-01 06:06 UTC, minju26 submitted a review, later dismissed

2024-10-01 07:07 UTC, Lucerna00 commented
말씀해 주신 피드백 반영하였습니다!

- JWT 관련 에러 상태 코드 변경
- SecurityConfig에서 메서드 참조 사용
- JwtAuthenticationFilter 위치 변경
- JWT 관련 util 클래스 추가 및 리팩토링

2024-10-01 07:19 UTC, minju26 commented
수고하셨습니다 :) 
에러 코드 수정 해뒀는데, 관련 PR 머지 된 후에 현재 PR 머지 되면 좋을 것 같습니다..!

2024-10-01 07:20 UTC, minju26 submitted a review, later dismissed

2024-10-01 08:33 UTC, dkswoals submitted a review, later dismissed
충돌 해결 후 머지 해주시면 될거 같습니다!
고생 많으셨습니다~!

2024-10-01 08:40 UTC, dkswoals approved these changes

2024-10-01 10:32 UTC, us4c0d3 approved these changes
늦게 확인해 죄송합니다..! 피드백 부분은 다른 분들이 충분히 남겨주셨고 반영도 잘 되어 준석님이 남겨주신 의논사항에 대해서만 말해보겠습니다.

> 어노테이션으로 사용자 정보를 가지고 올 때 id랑 member 객체 중 뭐가 더 나을까요?

현재 어노테이션을 통해 유저 정보가 필요한 부분은 모임 관련 정보가 사실상 전부입니다. `TeamRepository`에서 어떻게 구현하냐에 따라 다를 것 같은데, 현재는 JPQL로 구현되어 있어 id만 가지고 와도 충분하다고 생각됩니다. 만약 JPQL이 아니라 Jpa 기본 제공 메서드를 사용한다면 member 객체 정보가 더 구현에 편하다고 생각합니다.

지출 내역 관련 기능 개발중인데 Member 정보가 필요하다고 생각되면 그 때 pr이나 카톡으로 다시 의견 남기겠습니다.

> 역할에 따라서도 접근 허용을 설정할 수 있는데 ADMIN, NORMAL 등 사용자 역할이 필요할까요?

어드민페이지를 만들 것이라면 사용자 역할이 필요한데, 아직은 따로 계획이 없으므로 굳이 추가하지 않아도 될 것 같습니다. 재민님 의견대로 기본 기능 구현 후 기본, 유료, 관리자 등으로 권한을 나누면 좋을 것 같습니다.

2024-10-01 11:17 UTC, merged