Chore/issue#3 : CI 스크립트 작성
kakao-tech-campus-2nd-step3/Team23_BE pull request #4
Opened 2024-09-19 06:49 UTC by minju26

## PR
### ✨ 작업 내용
- weekly/* 브랜치에 pr 시 작동하는 빌드/테스트 스크립트를 작성했습니다.
- 성공 여부와 관계 없이, 완료 시 pr의 코멘트 형식으로 테스트 결과를 표시합니다.
- 실패한 경우, 오류가 발생한 라인에 표시하도록 했습니다.
- action 실행 마다 매번 Gradle을 다운받아 시간이 오래 걸리는 문제가 있어서 캐싱으로 개선해보았습니다.

### 🔍 참고 사항
- 일단 weekly 브랜치에서 잘 작동하는지 확인 후, 다른 브랜치에도 적용하도록 수정하도록 하겠습니다.
- 지금은 꼭 필요한 것 같진 않지만, 코드 커버리지 정도에 대한 표시도 추가할 수 있습니다.

### 🐞현재 버그
- 

### #️⃣ 연관 이슈(Git Close)
- #3 
___
### 😊 리뷰 규칙을 지킵시다
코드 리뷰는 `Pn`룰에 따라 작성하기.   
Reviewer가 피드백을 남길 때 Assignee에게 얼마나 해당 피드백에 대해 강조하고 싶은 지 표현하기 위한 규칙입니다.
- `P1` : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
- `P2` : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
- `P3` : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-09-19 07:36 UTC, us4c0d3 requested changes
수정사항 남겼습니다!

2024-09-19 07:36 UTC, us4c0d3 commented on .github/workflows/weekly-ci.yml
> +
P1: AWS에 배포를 할 것이기 때문에 distribution은 `corretto`를 사용하는 것을 권장합니다! 저도 가능하면 corretto를 통해 jar 생성 및 배포를 진행할 생각입니다.

2024-09-19 07:36 UTC, us4c0d3 commented on .github/workflows/weekly-ci.yml
> +      pull-requests: write
P1: issue는 read권한만 있어도 충분할 것 같습니다! 혹시 write 권한으로 설정한 이유가 있나요?

2024-09-19 07:36 UTC, us4c0d3 commented on .github/workflows/weekly-ci.yml
> +
P2: merge 등을 통한 오류가 발생할 수 있으므로 Master, Develop 브랜치도 추가하면 좋을 것 같습니다. 이하 코드들은 테스트 / 빌드까지이므로 타 브랜치를 추가해도 괜찮을 것 같습니다.

2024-09-20 06:04 UTC, minju26 commented on .github/workflows/weekly-ci.yml
> +
넵, `temurin`이 여러 환경에서 범용적으로 쓴다고 해서 사용해봤습니다.
`correto`가 특히 EC2에 최적화 된 JDK라고 알고 있는데, 아무래도 아마존에서 개발 한 만큼 다른 AWS 인프라와도 호환이 좋나보네요!

2024-09-20 06:06 UTC, minju26 commented on .github/workflows/weekly-ci.yml
> +      pull-requests: write
이슈에도 테스트 결과에 따라 어떤 작업을 해둘까 하다가 말았는데 그대로 뒀네요.
read 권한으로 충분 할 것 같아요!

2024-09-20 06:07 UTC, minju26 commented on .github/workflows/weekly-ci.yml
> +
넵 알겠습니다~

2024-09-20 13:04 UTC, Lucerna00 approved these changes, later dismissed
우석님이 피드백 잘 해주셔서 좋은 거 같습니다!

2024-09-20 13:04 UTC, Lucerna00 commented on .github/workflows/weekly-ci.yml
> +          cat application.properties
P3: cat은 없어도 되지 않을까요?

2024-09-20 13:09 UTC, us4c0d3 submitted a review, later dismissed
수고하셨습니다!

2024-09-20 13:09 UTC, us4c0d3 commented on .github/workflows/weekly-ci.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
No newline at end of file 에러입니다! 

[이 글](https://hyeon9mak.github.io/github-no-newline-at-a-end-of-file/)을 참고해주세요!

2024-09-20 13:30 UTC, minju26 commented on .github/workflows/weekly-ci.yml
> +          cat application.properties
포크하고 작업하다 보니, 업스트림 레포에 저장된 secret을 잘 가져 오는지 확인용입니다!
아직 민감한 정보는 없어서 넣어뒀어요

2024-09-20 13:36 UTC, minju26 commented on .github/workflows/weekly-ci.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
이런 에러가 있군요..! 추가했습니다 :)

2024-09-20 13:40 UTC, us4c0d3 approved these changes

2024-09-20 13:42 UTC, Lucerna00 approved these changes

2024-09-20 13:43 UTC, merged