Feature/issue#28: 모임 초대 수락 -> 모임 참여 API 구현
kakao-tech-campus-2nd-step3/Team23_BE pull request #42
Opened 2024-10-01 15:14 UTC by minju26

## PR
### ✨ 작업 내용
- 모임 초대 받은 사용자가 초대에 수락하여 모임 참여하는 api

### 🔍 참고 사항
- 일단 API 명세에 따라 `memberId`를 받고 있는데, 어차피 토큰에 인증 된 멤버 정보(id)가 있을 예정이라 리팩토링 시 반영하도록 하겠습니다.
- swagger에 명시할 내용을 관리하기 위해 컨트롤러의 interface를 정의하였고, `docs` 라는 패키지에 넣어두었습니다.

### ⚠️ 의논 필요
- 컨트롤러 인터페이스 관리 `controller.docs` 괜찮나요?! 

### 🐞현재 버그
X

### #️⃣ 연관 이슈(Git Close)
- #28 
___
### 😊 리뷰 규칙을 지킵시다
코드 리뷰는 `Pn`룰에 따라 작성하기.   
Reviewer가 피드백을 남길 때 Assignee에게 얼마나 해당 피드백에 대해 강조하고 싶은 지 표현하기 위한 규칙입니다.
- `P1` : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
- `P2` : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
- `P3` : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-10-01 17:32 UTC, us4c0d3 requested changes
API 명세에 대한 정보는 controller에만 필요하니까 controller.docs는 좋다고 생각합니다!
남긴 의견 확인해주시고 ERD와 코드 둘 중 하나는 수정해서 다시 리퀘스트 해주세요~

혹시 ERD 수정이 안된다면 카톡남겨주세요!

2024-10-01 17:32 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/domain/TeamMember.java
> +    public void acceptInvite() {
P2: `isInviteAccepted`는 ERD의 `is_invited` 필드를 의미한 것일까요? 문서와 달라 직관적으로 이해하기 어려울 수 있습니다. ERD와 코드 중 하나를 수정해서 통일해주세요!

2024-10-01 17:32 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/service/MemberService.java
> +
P3: team과 member를 teamMember 호출을 위해서만 사용하고 있는데, 그렇다면 `findTeamMemberByTeamAndMember`에 JPQL로 id만 사용하는 것은 어떨까요?

2024-10-02 03:10 UTC, dkswoals requested changes
고생하셨습니다!
수정 사항이랑 질문 남겨드렸습니다!
의견에 대해서는 controller.doc 동의합니다!

2024-10-02 03:10 UTC, dkswoals commented on src/main/java/kappzzang/jeongsan/repository/MemberRepository.java
> +}
(궁금) 아래의 teamRepository와 동일하게 이미 제공되어지는`findById`를 사용하지 않으신 이유가 있으신가요?

2024-10-02 03:10 UTC, dkswoals commented on src/main/java/kappzzang/jeongsan/domain/TeamMember.java
>      private Boolean isOwner;
P2: 이 부분도 ERD와 통일하는게 좋을거 같아요

2024-10-02 09:08 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/domain/TeamMember.java
> +    public void acceptInvite() {
음 ERD와 다르게 변경된 필드명은 엔티티 클래스 작성 PR에 다 적어 놨어서 다들 알고 계신 줄 알았네요..! 
권한 설정 바꿔주시면 PR에 적어둔 내용들 ERD에 반영 해두겠습니다~

2024-10-02 09:16 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/service/MemberService.java
> +
음.. 좀 더 깔끔할 것 같긴 합니다! 다만 멤버와 팀에 대해서 개별적인 예외 처리가 불가능해질 것 같습니다.
멤버는 추후에 request body 말고 authentication을 사용하도록 수정하면, 필터를 거쳐 이미 인증되었을 것 같고.. 팀은 따로 예외 처리가 필요할 것 같네요

authentication 사용하도록 리팩토링 할 때 이 부분도 고려해보도록  하겠습니다!

2024-10-02 09:18 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/domain/TeamMember.java
>      private Boolean isOwner;
ERD에 반영해 두도록 하겠습니다~

2024-10-02 09:20 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/repository/MemberRepository.java
> +}
음.. 글쎄요... 좀 더 명확한 이름..?😅

2024-10-02 09:30 UTC, us4c0d3 approved these changes
리팩토링할 때 다시 얘기하면 될 것 같습니다 수고하셨습니다! 👍

2024-10-02 09:54 UTC, dkswoals approved these changes
수고하셨습니다~!

2024-10-02 14:37 UTC, merged