Feature/issue#41: 카카오 토큰을 이용한 로그인
kakao-tech-campus-2nd-step3/Team23_BE pull request #44
Opened 2024-10-02 18:57 UTC by Lucerna00

## PR
### ✨ 작업 내용
- 카카오 토큰으로 카카오 프로필 정보 가져오기
- 카카오 프로필 정보로 회원가입 및 로그인
- JWT 생성

### 🔍 참고 사항
- 일단 기존 API 명세와 달리 request는 카카오 액세스 토큰만으로 구성하였습니다.
- 카카오 토큰 저장은 구현하지 않았습니다. (임시로 member의 kakaoToken 필드를 삭제하였고, 안드로이드 분들과 좀 더 얘기해 보겠습니다.)
- 카카오 회원번호를 member id로 설정하였습니다.

### ⚠️ 의논 필요
- 카카오 회원번호가 고유한 값이므로 기존 member id를 카카오 회원번호로 대체하면 편하고 좋을 것 같습니다.
- 카카오 프로필의 닉네임과 사진이 수시로 바뀔 수도 있다고 생각하는데 로그인 시 해당 데이터를 업데이트해야 할까요?

### 🐞현재 버그
X

### #️⃣ 연관 이슈(Git Close)
- close #41 
___
### 😊 리뷰 규칙을 지킵시다
코드 리뷰는 `Pn`룰에 따라 작성하기.   
Reviewer가 피드백을 남길 때 Assignee에게 얼마나 해당 피드백에 대해 강조하고 싶은 지 표현하기 위한 규칙입니다.
- `P1` : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
- `P2` : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
- `P3` : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-10-03 09:57 UTC, dkswoals requested changes
고생 많으셨습니다!
몇가지 수정사항 남겨드렸으니 확인 부탁드립니다

남겨주신 의견에 대해서는
1. 카카오 ID를 맴버 ID로 사용하는거 동의합니다!
2. 여러 방법이 있겠지만 우선은 로그인 요청 시에 프로필을 갱신시키는게 좋아 보입니다!
(이후 특정 주기마다 프로필 갱신하는 방식을 고려해봐도 좋을 것 같습니다)

2024-10-03 09:57 UTC, dkswoals commented on src/main/java/kappzzang/jeongsan/dto/response/LoginResponse.java
> +}
P2: 자바 컨벤션(카멜 케이스) 반영 부탁드립니다!

2024-10-03 09:57 UTC, dkswoals commented on src/main/java/kappzzang/jeongsan/global/client/dto/response/KakaoProfileResponse.java
> +    }
이 부분도 동일합니다

2024-10-03 09:57 UTC, dkswoals commented on src/main/java/kappzzang/jeongsan/global/client/kakao/KakaoApiClient.java
> +    }
P3: 이미 onStatus에서 처리되는 HttpClientErrorException을 따로 try catch문으로 잡고 RuntimeException을 던지는 이유가 있으신가요?

2024-10-03 09:57 UTC, dkswoals commented on src/main/java/kappzzang/jeongsan/dto/request/LoginRequest.java
> +}
P3: 입력값에 대한 유효성 검증을 추가하는건 어떨까요?

2024-10-03 10:12 UTC, dkswoals commented on src/main/java/kappzzang/jeongsan/dto/response/LoginResponse.java
> +}
드레그를 깜빡해서 코드가 많이 잘렷네요..

2024-10-03 10:29 UTC, minju26 reviewed
수고하셨습니다😊 간단한 코멘트 남겨뒀습니다 

추가로 의견과 의문을 남기자면,
- 처음엔 카카오 아이디가 유일하다면 저희 서비스 아이디로도 사용하면 되겠다 싶었는데.. 다시 생각해보니 **중요 정보인 회원id가 외부 서버에 의존하게 된다는 점**에서, 기존에 정한 대로 별도의 필드로 구분하여 **저희 서비스가 관리하는 회원id**를 쓰는 것이 좋겠다는 의견입니다.
- 프로필은.. 일단 업데이트 없이 그냥 가도 될 것 같습니다
- **Member** 엔티티에서 `kakaoToken` 필드를 아예 지워버리신 이유가 궁금합니다! 
(엔티티 클래스는 실행 중 문제가 없다면 어떻게 될 지 모르니, 지우는 것 보다 초기에 정한 형태를 유지하는 게 좋을 것 같은..)

2024-10-03 10:29 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/global/client/kakao/KakaoProfileProperties.java
> +@ConfigurationProperties(prefix = "kakao.profile")
엇 properties 파일에 추가 하셨나요?! 노션엔 없어서 제대로 액션 시크릿 업데이트가 된건지 확인차 여쭤봅니다

2024-10-03 10:29 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/global/client/dto/response/KakaoProfileResponse.java
> +    KakaoAccount kakao_account
P2: 프로젝트 전체적으로 camel case를 사용하고 있으므로 통일해주시면 좋을 것 같습니다! `@JsonProperty`를 사용하면 네이밍 규칙을 지정할 수 있어 외부에서 받아오는 json객체를 적절히 처리할 수 있습니다
(`LoginResponse`에도 snake case가 있네요)

2024-10-03 10:44 UTC, us4c0d3 requested changes
> 카카오 회원번호가 고유한 값이므로 기존 member id를 카카오 회원번호로 대체하면 편하고 좋을 것 같습니다.

이 부분과 관련해서 안드 분들과 얘기 했을 때 카카오 로그인 시 카카오측에서 앱 기준의 고유한 id를 제공해준다고 합니다. 그래서 카카오 기능 개발할 때 응답 데이터를 공유해주시기로 해서 이를 보고 결정하면 될 것 같습니다. 현재 고민하고 있는 식별자는 1. id, 2. uuid입니다.

> 카카오 프로필의 닉네임과 사진이 수시로 바뀔 수도 있다고 생각하는데 로그인 시 해당 데이터를 업데이트해야 할까요?

현재는 업데이트는 없어도 괜찮을 것 같습니다!(개발 우선순위 문제)

그와 별개로 의견을 남기자면, 앱의 경우 구현에 따라 다르겠지만 매번 로그인을 해야 될 수도 있고 로그인 정보를 로컬에 유지하는 경우도 있어 로그인시 데이터 업데이트의 경우 시점이 모호해질 수 있습니다(극단적인 경우 업데이트가 없을 수 있음)

2024-10-03 10:44 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/dto/response/LoginResponse.java
> +    String token
P2: 클래스에 `@JsonNaming(SnakeCaseStrategy.class)`를 사용하면 카멜케이스 -> 스네이크케이스로 변환됩니다!

2024-10-03 10:44 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/global/client/kakao/KakaoApiClient.java
> +    }
P2: JeongsanException 또는 log.error를 이용해 구체적인 에러 로그를 보여주세요

2024-10-03 10:44 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/service/MemberService.java
> +        memberRepository.save(member);
(단순 의견): 각 메서드 명이 명확해서 주석은 없어도 될 것 같습니다!

2024-10-03 13:00 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/dto/response/LoginResponse.java
> +}
네 카멜 표기로 통일하였습니다!

2024-10-03 13:00 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/global/client/kakao/KakaoApiClient.java
> +    }
맞네요.. 핸들러가 있는데 try-catch문을 사용했네요
수정하였습니다!

2024-10-03 13:00 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/global/client/kakao/KakaoProfileProperties.java
> +@ConfigurationProperties(prefix = "kakao.profile")
제가 깜빡했네요..
카카오 관련 시크릿 노션에 추가하였습니다

+) 개발할 때 `KakaoToken` 엔티티 자체를 사용할 필요가 없다고 생각하여 삭제하였는데, 성급했던 것 같아 일단 다시 추가해 두었습니다!

2024-10-03 13:00 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/global/client/dto/response/KakaoProfileResponse.java
> +    KakaoAccount kakao_account
네 카멜 표기로 통일하였고 카카오 응답에는 `@JsonProperty`를 사용하였습니다

2024-10-03 13:00 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/dto/response/LoginResponse.java
> +    String token
네 카멜 표기로 바꾸고 `@JsonProperty` 적용하였습니다

2024-10-03 13:00 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/global/client/kakao/KakaoApiClient.java
> +    }
제가 실수로 핸들러가 있는데 try-catch문을 또 사용했네요
 try-catch문을 제거하였습니다

2024-10-03 13:00 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/service/MemberService.java
> +        memberRepository.save(member);
동의합니다
주석 제거하겠습니다!

2024-10-03 13:02 UTC, Lucerna00 commented
피드백 해주셔서 감사합니다!

<br>

다음은 의논 사항에 대해 정리한 내용입니다.

> 카카오 회원번호가 고유한 값이므로 기존 member id를 카카오 회원번호로 대체하면 편하고 좋을 것 같습니다.

저희 서비스가 카카오 로그인이 필수이고, 카카오에선 **앱 단위**로 **고유번호**를 발급해 주므로 카카오 관련 id를 member 식별자로 사용해도 된다고 생각하였습니다. 정확한 식별자는 안드로이드 분들과 얘기 후 결정하겠습니다.

> 카카오 프로필의 닉네임과 사진이 수시로 바뀔 수도 있다고 생각하는데 로그인 시 해당 데이터를 업데이트해야 할까요?

일단 기능 개발이 우선이기에 닉네임 및 사진 업데이트는 고려하지 않겠습니다.

> `KakaoToken` 엔티티에 대하여

저번 회의에선 토큰 만료 시간 및 refresh 토큰 때문에 카카오 토큰 정보를 저장해야 한다는 의견이 있었습니다. 하지만 현재 재발급된 카카오 토큰을 주고받는 API가 없기도 하고 카카오 토큰은 안드로이드 SDK에서 관리해도 될 것 같아 카카오 토큰 정보를 저장하지 않았습니다. 이 부분도 안드로이드 분들과 얘기해 봐야겠습니다.

2024-10-03 13:05 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/dto/response/LoginResponse.java
> +    String token
네 카카오 응답에는 @JsonProperty를 사용해 보았습니다

2024-10-03 13:18 UTC, minju26 commented
수고하셨습니다
의논 사항에 대해서는 회의 때 더 이야기 해봅시다~

2024-10-03 13:19 UTC, minju26 submitted a review, later dismissed

2024-10-03 13:21 UTC, dkswoals submitted a review, later dismissed
수고 많으셨습니다~!!

2024-10-03 18:08 UTC, us4c0d3 approved these changes
수고하셨습니다!

2024-10-04 02:33 UTC, dkswoals approved these changes

2024-10-04 02:48 UTC, merged