Feature/issue#55: 모임의 멤버 초대 현황 조회 API
kakao-tech-campus-2nd-step3/Team23_BE pull request #56
Opened 2024-10-07 08:42 UTC by minju26

## PR
### ✨ 작업 내용
- 모임의 멤버 초대 현황 조회 API

### 🔍 참고 사항
- swagger에 같은 에러 코드인 경우, 하나만 표시되는 문제가 있지만 일단 작성해뒀습니다.
- 해당 문제의 경우, 커스텀하거나 description에 작성하거나.. 등등 회의를 통해 구체적인 것을 정하면 될 것 같습니다.
- 테스트 코드에서의 사용을 위해 `TeamMember` 엔티티 클래스에 `@AllArgsConstructor` 를 추가하게 되었습니다.

### ⚠️ 의논 필요
X

### 🐞현재 버그
X

### #️⃣ 연관 이슈(Git Close)
- close #55 
___
### 😊 리뷰 규칙을 지킵시다
코드 리뷰는 `Pn`룰에 따라 작성하기.   
Reviewer가 피드백을 남길 때 Assignee에게 얼마나 해당 피드백에 대해 강조하고 싶은 지 표현하기 위한 규칙입니다.
- `P1` : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
- `P2` : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
- `P3` : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-10-07 17:56 UTC, Lucerna00 requested changes
사소한 피드백만 반영해 주시면 될 것 같습니다
수고하셨습니다!

2024-10-07 17:56 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/controller/TeamController.java
> +        return JeongsanApiResponse.success(SuccessType.INVITATION_STATUS_LOADED, data);
P2: API 명세에 따르면 위 형식이 맞으나 현재 DTO는 밑에 형식입니다. 둘 중 하나를 선택해야 할 것 같습니다
```
"data": {
    "memberList": [
        {
            "memberId" : "멤버 ID",
            "nickname": "이름",
            "profileImage: "이미지",
            "isInviteAccepted": "초대완료여부"
        },
    ]
}
```

```
"data": [
    {
        "memberId" : "멤버 ID",
        "nickname": "이름",
        "profileImage: "이미지",
        "isInviteAccepted": "초대완료여부"
    },
]
```

2024-10-07 17:56 UTC, Lucerna00 commented on src/test/java/kappzzang/jeongsan/repository/TeamMemberRepositoryTest.java
> +    void findInvitationStatusByTeamId_ShouldReturnCorrectList() {
P2: `@DisplayName`을 추가하면 좋겠습니다

2024-10-07 17:56 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/service/TeamService.java
> +    public List<InvitationStatusResponse> getInvitationStatus(Long teamId) {
(궁금): `@Transactional(readOnly = true)`를 사용하지 않은 이유가 있을까요??

2024-10-07 17:56 UTC, Lucerna00 commented on src/main/java/kappzzang/jeongsan/service/TeamService.java
> +            .orElseThrow(() -> new JeongsanException(ErrorType.INVITATION_STATUS_NOT_FOUND));
(궁금): 조건문 대신 optional, filter를 사용한 이유가 가독성 때문인가요??

2024-10-08 04:38 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/controller/TeamController.java
> +        return JeongsanApiResponse.success(SuccessType.INVITATION_STATUS_LOADED, data);
음.. 그러네요 data에 list만 있다면 wrapper클래스가 있는게 좋은지 안드와 이야기해볼게요!

2024-10-08 04:48 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/service/TeamService.java
> +    public List<InvitationStatusResponse> getInvitationStatus(Long teamId) {
단순한 읽기 작업이기도 하고, 저희 서비스가 소규모 애플리케이션이라..
조회 메서드에 해당 어노테이션에 대한 인지 자체를 안하고 있었네요

성능상 중요한 부분에는 명확히 있으면 좋을 것 같습니다! 
아니면, 있어서 나쁠 건 없으니 팀 코딩 컨벤션으로 얘기해봐도 좋을 것 같네요~

2024-10-08 04:51 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/service/TeamService.java
> +            .orElseThrow(() -> new JeongsanException(ErrorType.INVITATION_STATUS_NOT_FOUND));
넵 상황에 따라 다르긴 하겠지만, 개인적으로 조건문을 꼭 써야만 표현되는 부분이 아니라면 메서드 체이닝을 사용합니다!

2024-10-08 06:25 UTC, us4c0d3 requested changes
`@AllArgsConstructor`에 관한 의견 하나 남겼습니다! 확인해주세요~

2024-10-08 06:25 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/domain/TeamMember.java
>      @Id
P1: AllArgsConstructor를 사용하면 자동으로 생성되는 id와 BaseEntity의 상위 필드 포함 모든 필드에 대한 생성자를 추가하기 때문에 문제가 생깁니다. 혹시 테스트에서 id 필드를 지정할 필요가 있어서 사용을 하셨나요? 그렇다면 리플렉션 사용을 추천드립니다

2024-10-08 06:25 UTC, us4c0d3 commented on src/test/java/kappzzang/jeongsan/repository/TeamMemberRepositoryTest.java
> +        entityManager.merge(teamMember1);
P2: 리플렉션을 사용한 예시 코드입니다

```java
private void setIdUsingReflection(Object entity, Long id) {
    try {
        Field idField = entity.getClass().getDeclaredField("id");
        idField.setAccessible(true);
        idField.set(entity, id);
    } catch (Exception e) {
        System.err.println(e.getMessage());
    }
}
```

```java
// 자동 생성 데이터 제외 생성자 사용
member1 = new Member("user1", "nickname1", "profile1", "token1", kakaoToken, List.of(new TeamMember()));
setIdUsingReflection(member1, 1L);
```

2024-10-08 06:49 UTC, minju26 commented on src/test/java/kappzzang/jeongsan/repository/TeamMemberRepositoryTest.java
> +        entityManager.merge(teamMember1);
오호 이렇게 할 수 있군요! 반영하도록 하겠습니다

2024-10-09 09:40 UTC, minju26 commented
`TeamMember` 엔티티에서 `@AllArgsConstructor` 를 사용한 이유는, id 지정보다는 단순히 모든 필드가 포함된 객체를 생성하기 위함이었습니다. 이 때 상위 클래스에 대해서는 미처 생각하지 못했네요..!
따라서 그냥 생성자를 사용하도록 수정했습니다

`리플렉션` 의 경우에는, 여러 이유로 인해 일반적으로 권장되지는 않는다고 합니다! 간단히 몇가지만 적어두자면 아래와 같습니다.
- 성능저하(일반적인 메서드 호출이나 필드 접근보다 느림, JVM이 최적화하기 어려움)
- 런타임 오류 가능성(컴파일 시점의 타입 체크를 우회함)
- 캡슐화 위반(private 필드에 직접 접근 -> 보안 위험)

2024-10-09 09:41 UTC, minju26 commented on src/main/java/kappzzang/jeongsan/controller/TeamController.java
> +        return JeongsanApiResponse.success(SuccessType.INVITATION_STATUS_LOADED, data);
바로 data에 리스트 넣는 것으로 명세 수정했습니다~

2024-10-09 09:51 UTC, Lucerna00 approved these changes, later dismissed
수고하셨습니다!

2024-10-10 04:59 UTC, minju26 commented
`Member` 엔티티 수정 문제로 테스트 코드 주석 처리 했습니다. 이후 리펙토링 하며 수정하겠습니다!

2024-10-10 04:59 UTC, us4c0d3 approved these changes

2024-10-10 05:03 UTC, Lucerna00 approved these changes

2024-10-10 05:05 UTC, merged