Feature/issue#78: 지출 상태 변경(송금 대기 -> 완료) 기능 구현
kakao-tech-campus-2nd-step3/Team23_BE pull request #96
Opened 2024-10-30 05:20 UTC by dkswoals

## PR
### ✨ 작업 내용
- 지출 정산 상태 변경(송금 대기 -> 완료) 기능 구현
- 테스트 코드 작성

### 🔍 참고 사항
- 9주차 주간 회의때에 변경된 API 명세 기준으로 기능 구현하였습니다.
- `Expense`의 `changeStatusPending()`메서드의 경우 테스트를 위해 단순 구현하였습니다.
- 이후 `changeStatusPending()` 변경 시 ExpenseServiceTest가 작동하지 않게 된다면 전체 코드 주석 처리 부탁드립니다.

### ⚠️ 의논 필요
- X

### 🐞현재 버그
- X

### #️⃣ 연관 이슈(Git Close)
- close #78 
___
### 😊 리뷰 규칙을 지킵시다
코드 리뷰는 `Pn`룰에 따라 작성하기.   
Reviewer가 피드백을 남길 때 Assignee에게 얼마나 해당 피드백에 대해 강조하고 싶은 지 표현하기 위한 규칙입니다.
- `P1` : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
- `P2` : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
- `P3` : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)

2024-10-30 12:21 UTC, us4c0d3 requested changes
의견 남겼습니다! expenseList를 불러오는 로직에 안정성이 부족한 것 같아 request change 남깁니다

2024-10-30 12:21 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/global/common/enumeration/ErrorType.java
> +        "요청 목록에 존재하지 않는 지출이 포함 되어있습니다."),
P3: 에러 코드에서는 복수형일 필요는 없을 것 같습니다!(단순 의견입니다)

2024-10-30 12:21 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/service/ExpenseService.java
> +        expenses.forEach(Expense::changeStatusComplete);
P1: expense 데이터 확인을 단순히 크기 비교를 통해 한다면 요청한 유저가 접근할 수 없는 모임의 지출 내역도 부를 위험성이 있을 것 같습니다(자신이 속한 모임이 아닌 id가 요청에 포함될 수 있음). 요청에 jwt 토큰에서 userId를 얻을 수 있고, 엔드포인트에 teamId가 있으니 이를 활용하면 좀 더 안정적으로 확인할 수 있을 것 같습니다.

2024-10-30 14:43 UTC, dkswoals commented on src/main/java/kappzzang/jeongsan/service/ExpenseService.java
> +        expenses.forEach(Expense::changeStatusComplete);
좋은 의견입니다!! 반영하겠습니다

2024-10-30 14:48 UTC, minju26 submitted a review, later dismissed
수고하셨습니다~

2024-10-30 22:16 UTC, us4c0d3 approved these changes, later dismissed
수고하셨습니다!

2024-10-30 22:16 UTC, us4c0d3 commented on src/main/java/kappzzang/jeongsan/domain/Expense.java
> +        }
P3: 클래스의 멤버 변수를 부르는 것인데 getter를 쓸 필요가 있을까요? 그냥 `this.team.getId().equals(teamId)`와 같은 형식이어도 될 것 같습니다

2024-10-30 23:17 UTC, dkswoals commented on src/main/java/kappzzang/jeongsan/domain/Expense.java
> +        }
아 맞네요..! 반영하겠습니다

2024-10-30 23:23 UTC, us4c0d3 approved these changes

2024-10-31 04:50 UTC, Lucerna00 approved these changes

2024-10-31 05:50 UTC, merged